### PR TITLE
fix: return erroring exit codes with the set exit value

### LINKED ISSUE #137: Bug report: Exit code is set to `0` when exiting with an error
**Describe the bug**

Warping to paths that aren't set, or other similar errors, will print an error that isn't returned in an exit code without debug mode being set. When debug mode is set, the entire shell seems to exit, not just the warp attempt!

**To reproduce**

Attempt to warp to a place that might not exist: 👾 

```zsh
$ cd
$ wd moon && ./monolith
 * Unknown warp point 'moon'
zsh: no such file or directory: ./monolith
$ wd moon
 * Unknown warp point 'moon'
$ echo $?
0
```

**Expected behavior**

The exit code should surface an error:

```zsh
$ wd moon
 * Unknown warp point 'moon'
$ echo $?
1
```

**Desktop**

 - zsh version: zsh 5.9 (aarch64-apple-darwin23.6.0)
 - wd version: wd version: 0.8.0

**Additional context**

In the current behaviors above, I'm not sure what the `monolith` script might enact but I don't think an attempt to call it since we'd still be in the $HOME directory 👽 💨

### PR DESCRIPTION
**Pull request by zimeg**
### Summary

This PR returns the `$WD_EXIT_CODE` to whatever it might be set to when this program completes for all cases, not just the testing done in debug mode, to fix #137.

### Preview

With the changes of this branch, the following commands continue to **warp** or exit with the error code:

```zsh
$ wd list
...
$ cd
$ wd [example]
$ echo $?
0
$ pwd
$ wd bogus
 * Unknown warp point 'bogus'
$ echo $?
1
```

### Notes

A `return` is preferred to `exit` to avoid quitting the sourced shell session, but I'm not certain about this change so thoughts or more testing for this would be nice!

I've tested both errors and successful warps on the following setups, and feel mostly confident with these:

- zsh 5.9 (aarch64-apple-darwin23.6.0)
- zsh 5.9 (x86_64-pc-linux-gnu)

The unit testing asserts also seem to have been working as expected since `$wd_debug_mode` is set to `true` in tests and this continues to remain the case! An update was also made to unset a set debug mode variable here too, while keeping the same tested exit behavior.

### CODE REVIEW

**Comment by zimeg** [comment]
Oh I did also notice this section in the `README.md` which is giving me a few questions:

> - Force exit with return code after running. This is not default, as it will exit your terminal, though required for testing/debugging.
>
> ```
> wd --debug <command>
> ```

I realize removing the current forced `exit` is a breaking change at the moment (and adding this back is no problem) but I was wondering if the forced `exit` is just meant for use in testing or elsewhere too?

In a quick search I didn't find other references to `--debug` in the script, and might expect to match the current exiting in my own commands with something like this if I missed the option:

```sh
$ wd bogus || exit 1
```

Not necessarily meaning to suggest that forced exits of the `--debug` option are removed, but I do find it interesting that the tests work as expected with just a `return`. I'm open to updating either the script or docs with whatever seems best!

**Comment by zimeg** [comment]
@alpha-tango-kilo 🫡 Then it might soon be farewell to the `--debug` flag. I'll make this change in a separate PR that points to this branch to order commits, but please feel free to merge however you'd like!

When testing this change, I was respawning a bunch of shells to exit or quit after a direct `source wd.sh [cmd]`, but I find similar behavior when using the function approach of [the manual installation](https://github.com/mfaerevaag/wd#manual) (though the latter avoids errors of a readonly `WD_VERSION`). Doing the direct `source wd.sh` **does** cause the unfortunate yot when using `exit` with these changes, same as with the function setup, but a session persists with an exit code using `return`.

I also checked and found that `return` works well with both the oh-my-zsh and manual installation approach! Totally agree that these are super important to check! 🧑‍🔬

**Comment by zimeg** [comment]
I'm finding that a PR with https://github.com/mfaerevaag/wd/pull/138/commits/a8d3fd52d3362fb6e8f6056488521f4058ac564e **into** this branch wouldn't show up for this repo - it'd be a forked PR to a forked repo 🍽️ 😋

I added those changes here instead since it still seems related to these changes, but please let me know if updates are needed!

**Comment by alpha-tango-kilo** [comment]
Released as v0.9.0, thanks for all your recent contributions!

**Comment by zimeg** [comment]
@alpha-tango-kilo Sweet! Likewise, thank you for all of the reviews 🙏

**Pull request merged**
